# Generated by Django 5.2.7 on 2025-11-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('value', models.CharField(max_length=100, verbose_name='Значение (число или текст)')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='ПУТЕШЕСТВИЕ', max_length=200, verbose_name='Главный заголовок')),
                ('title_highlight', models.CharField(default='ВИЕ', max_length=50, verbose_name='Выделенная часть заголовка')),
                ('subtitle', models.CharField(default='на красную планету', max_length=200, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(default='Начать путешествие', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(default='#', max_length=200, verbose_name='URL кнопки')),
            ],
            options={
                'verbose_name': 'Контент главного экрана',
                'verbose_name_plural': 'Контент главного экрана',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
    ]
