# Generated by Django 5.2.7 on 2025-11-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фоновое изображение'),
        ),
    ]
